// Copyright (c) 2022 The Brave Authors. All rights reserved.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this file,
// you can obtain one at http://mozilla.org/MPL/2.0/.

import { ThemedStyledProps } from 'styled-components'

export default interface IThemeProps {
  name: string
  color: {
    gray10: string
    gray20: string
    gray30: string
    gray40: string
    gray50: string
    gray60: string
    gray70: string
    gray80: string
    gray90: string
    gray100: string
    gray110: string
    gray120: string
    primary10: string
    primary20: string
    primary30: string
    primary40: string
    primary50: string
    primary60: string
    primary70: string
    primary80: string
    primary90: string
    primary100: string
    primary110: string
    primary120: string
    secondary10: string
    secondary20: string
    secondary30: string
    secondary40: string
    secondary50: string
    secondary60: string
    secondary70: string
    secondary80: string
    secondary90: string
    secondary100: string
    secondary110: string
    secondary120: string
    red10: string
    red20: string
    red30: string
    red40: string
    red50: string
    red60: string
    red70: string
    red80: string
    red90: string
    red100: string
    red110: string
    red120: string
    yellow10: string
    yellow20: string
    yellow30: string
    yellow40: string
    yellow50: string
    yellow60: string
    yellow70: string
    yellow80: string
    yellow90: string
    yellow100: string
    yellow110: string
    yellow120: string
    green10: string
    green20: string
    green30: string
    green40: string
    green50: string
    green60: string
    green70: string
    green80: string
    green90: string
    green100: string
    green110: string
    green120: string
    blue10: string
    blue20: string
    blue30: string
    blue40: string
    blue50: string
    blue60: string
    blue70: string
    blue80: string
    blue90: string
    blue100: string
    blue110: string
    blue120: string
    lightBlue10: string
    lightBlue20: string
    lightBlue30: string
    lightBlue40: string
    lightBlue50: string
    lightBlue60: string
    lightBlue70: string
    lightBlue80: string
    lightBlue90: string
    lightBlue100: string
    lightBlue110: string
    lightBlue120: string
    violet10: string
    violet20: string
    violet30: string
    violet40: string
    violet50: string
    violet60: string
    violet70: string
    violet80: string
    violet90: string
    violet100: string
    violet110: string
    violet120: string
    pink10: string
    pink20: string
    pink30: string
    pink40: string
    pink50: string
    pink60: string
    pink70: string
    pink80: string
    pink90: string
    pink100: string
    pink110: string
    pink120: string
    teal10: string
    teal20: string
    teal30: string
    teal40: string
    teal50: string
    teal60: string
    teal70: string
    teal80: string
    teal90: string
    teal100: string
    teal110: string
    teal120: string
    tor10: string
    tor20: string
    tor30: string
    tor40: string
    tor50: string
    tor60: string
    tor70: string
    tor80: string
    tor90: string
    tor100: string
    tor110: string
    tor120: string
    white: string
    legacy: {
      background01: string
      background02: string
      text01: string
      text02: string
      text03: string
      interactive01: string
      interactive02: string
      interactive03: string
      interactive04: string
      interactive05: string
      interactive06: string
      interactive07: string
      interactive08: string
      disabled: string
      divider01: string
      focusBorder: string
    }
  }
}

export type BraveThemedStyledProps<T> = ThemedStyledProps<T, IThemeProps>
